version: "3.8"

services:
  backend:
    image: your-dockerhub-username/backend:latest
    container_name: backend-prod
    restart: always
    env_file: ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  frontend:
    image: your-dockerhub-username/frontend:latest
    container_name: frontend-prod
    restart: always
    env_file: ./frontend/.env
    ports:
      - "80:80"
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    container_name: mongodb-prod
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

volumes:
  mongo-data:
