name: Deploy to Hostinger VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Backend Image
        run: |
          docker build -t your-dockerhub-username/backend:latest ./backend
          docker push your-dockerhub-username/backend:latest

      - name: Build and Push Frontend Image
        run: |
          docker build -t your-dockerhub-username/frontend:latest ./frontend
          docker push your-dockerhub-username/frontend:latest

      - name: Deploy to Hostinger VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOSTINGER_VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/your-app-folder+
            docker-compose down
            docker pull your-dockerhub-username/backend:latest
            docker pull your-dockerhub-username/frontend:latest
            docker-compose up -d
            
            # Restart Nginx to apply any new configurations
            sudo systemctl restart nginx
